version: '{build}'
clone_depth: 25

branches:
  only:
    - master
    - devel
    - appveyor
    - /devel.*/
    - /.*-avy/
    - /.*-ci/

environment:
  PYTHONWARNINGS: ignore::DeprecationWarning
  PATH: '%APPDATA%\Python\%PYTHON%\Scripts;C:\%PYTHON%%ARCH%\Scripts;C:\%PYTHON%\Scripts;C:\Program Files (x86)\Graphviz2.38\bin;%PATH%'
  matrix:
  - PYTHON: Python36
    EXTRA_ARGS: -m llvm
  - PYTHON: Python37
    EXTRA_ARGS: -m llvm
  - PYTHON: Python36
    ARCH: -x64
    PYTORCH: 1.0.1-cp36-cp36m
  - PYTHON: Python37
    ARCH: -x64
    PYTORCH: 1.0.1-cp37-cp37m

install:
  - if not exist graphviz-2.38.msi appveyor-retry curl https://graphviz.gitlab.io/_pages/Download/windows/graphviz-2.38.msi -o graphviz-2.38.msi
  - msiexec.exe /i graphviz-2.38.msi /passive
  - pip --version
  - pip install --user -U pip
  - pip --version
  # certifi upgrade is needed by pytest-profiling (it does not set the dependencies right)
  # numpy 1.16 gets pulled by leabra below and pnl downgrades it to <1.16 later
  - pip install --user -U certifi "numpy<1.16"
  - pip install --user git+https://github.com/benureau/leabra.git@master

  # pytorch does not distribute windows packages over pypi.
  # Install it directly.
  - if not "%PYTORCH%" == "" pip install --user http://download.pytorch.org/whl/cpu/torch-%PYTORCH%-win_amd64.whl

  # Remove pytorch from requirements if none is available
  - if "%PYTORCH%" == "" (findstr /V torch < dev_requirements.txt > tmp_req && move /Y tmp_req dev_requirements.txt)

  - pip install --user -e .[dev]

cache:
    - '%LOCALAPPDATA%\pip\Cache'
    - 'graphviz-2.38.msi'

build: off

test_script:
  - pytest --junit-xml=tests_out.xml -n auto --strict-markers %EXTRA_ARGS%

on_finish:
  # Upload tests to appveyor overview
  - appveyor-retry curl -X POST -F "file=@tests_out.xml" https://ci.appveyor.com/api/testresults/junit/%APPVEYOR_JOB_ID%
