branches:
  only:
    - master
    - devel
    - /devel-.*/
    - /travis.*/
    - /ci-.*/

language: shell
os: linux
dist: bionic

arch:
  - amd64
  - ppc64le

env:
  jobs:
    - PYTHON=3.8
    - PYTHON=3.7
    - PYTHON=3.6
  global:
    - PYTHONWARNINGS="ignore::DeprecationWarning"
    - PIP_PROGRESS_BAR="off"
    - COVERALLS_PARALLEL=true

# Cache downloaded and built python packages
# This needs to be explicit, 'cache: pip' only works with 'language: python'
cache:
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - graphviz

before_install:
  - |
    # Install venv on Linux using Ubuntu distributed python
    if [ "$TRAVIS_CPU_ARCH" != "amd64" ]; then
      # There are a lot fewer wheels distributed for non-x86 architectures.
      # We end up building a lot of them locally, install dev packages
      EXTRA_PKGS="build-essential gfortran llvm-8-dev libfreetype6-dev libjpeg-dev liblapack-dev zlib1g-dev"
      # Export LLVM_CONFIG for llvmlite
      export LLVM_CONFIG=llvm-config-8
      # Cython is needed to build scikit-learn
      EXTRA_PIP="cython"
    fi
    # distutils and lib2to3 are only needed for python3.8
    # https://bugs.launchpad.net/ubuntu/+source/python3.8/+bug/1851684
    sudo apt-get install -y python$PYTHON-dev python$PYTHON-venv python3-distutils python3-lib2to3 $EXTRA_PKGS
    python$PYTHON -m venv $HOME/venv

  # Provide fake xdg-open
  - echo "#!/bin/sh" > $HOME/venv/bin/xdg-open
  - chmod +x $HOME/venv/bin/xdg-open

  # The rest of the setup is common for all environments
  - source $HOME/venv/bin/activate

  - python --version
  - pip install -U pip wheel
  - pip --version
  - |
    # Install undeclared dependencies
    if [ "x$EXTRA_PIP" != "x" ]; then
      pip install $EXTRA_PIP
    fi

install:
  - pip install coveralls
  - pip install git+https://github.com/benureau/leabra.git@master
  - pip install -e .[dev]


script:
  - if [ "x$RUN_COV" != "x" ] ; then echo "Running with coverage"; export COV_ARGS="--cov=psyneulink"; else echo "Running without coverage"; export COV_ARGS=""; fi
  - if [ "$TRAVIS_CPU_ARCH" == "ppc64le" ] ; then export MAX_PROCESSES="--maxprocesses=6"; fi
  - pytest -n auto -p no:logging --verbosity=0 $COV_ARGS $MAX_PROCESSES

after_script:
  - if [ "x$RUN_COV" != "x" ] ; then coveralls; fi

notifications:
  webhooks: https://coveralls.io/webhook
