branches:
  only:
    - master
    - devel
    - /devel-.*/
    - /travis.*/

language: python

python:
    - 3.6
    - 3.7

os: linux
dist: xenial

env:
  global:
    - PYTHONWARNINGS="ignore::DeprecationWarning"

# Cache downloaded(built) python packages
cache:
  pip

addons:
  apt:
    packages:
      - graphviz

matrix:
  include:
  - os: osx
    python: 3.6
    language: minimal
    env: PYTHON=3.6.8
    # Cache pip and homebrew downloads
    cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - $HOME/Library/Caches/pip

  - os: osx
    python: 3.7
    language: minimal
    env: PYTHON=3.7.4
    # Cache pip and homebrew downloads
    cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - $HOME/Library/Caches/pip

before_install:
  - |
    # OSX Python is not directly supported on travis
    # Install it manually from python.org
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      # homebrew plugin is not working correctly
      # https://travis-ci.community/t/xcode-8-3-homebrew-outdated-error/3798
      HOMEBREW_NO_AUTO_UPDATE=1 brew install graphviz
 
      FILE=python-$PYTHON-macosx10.9.pkg
      if [ ! -f $HOME/Library/Caches/$FILE ]; then
        curl -#  https://www.python.org/ftp/python/$PYTHON/$FILE -o $HOME/Library/Caches/$FILE
      fi
      sudo installer -pkg $HOME/Library/Caches/$FILE -target /
      python3 --version
      python3 -m pip --version

      # Deploy new virtualenv to match travis setup
      echo "Deploying new python venv"
      python3 -m pip  install virtualenv
      python3 -m venv $HOME/venv
      source $HOME/venv/bin/activate

      # Upgrade pip
      pip install -U pip
    fi
  - python --version
  - pip --version

install:
  # Downgrade numpy early if needed.
  - pip install -U 'numpy<1.17'
  - pip install coveralls
  - pip install git+https://github.com/benureau/leabra.git@master
  # Travis bundles pytest 4.3.1 in Linux Xenial, new pytest-xdist
  # requires pytest>=4.4.0, and the dependencies are broken
  - pip install -U pytest
  - pip install -e .[dev]


script:
  - pytest -n auto --strict-markers -p no:logging --cov=psyneulink

after_script:
  - COVERALLS_PARALLEL=true coveralls

notifications:
  webhooks: https://coveralls.io/webhook
