name: 'Install local pnl package'
description: 'Install PsyNeulink dependencies and editable PNL package'
inputs:
  features:  # id of input
    description: 'PsyNeuLink features to install'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: Shared dependencies
      shell: bash
      run: |
        # explicitly install numpy (https://github.com/pypa/pip/issues/9239)
        python -m pip install --upgrade pip wheel $(grep numpy requirements.txt)
        pip install -e .[${{ inputs.features }}]

