name: 'Install local pnl package'
description: 'Install PsyNeulink dependencies and editable PNL package'
inputs:
  features:  # id of input
    description: 'PsyNeuLink features to install'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: OS dependencies
      shell: bash
      env:
        RUNNER_OS: ${{ runner.os }}
        HOMEBREW_NO_AUTO_UPDATE: 1
      # Composited actions can't use step conditionals.
      run: |
        case "$RUNNER_OS" in
          macOS*) brew install graphviz ;;
          Linux*) sudo apt-get install -y graphviz ;;
          Windows*) choco install --no-progress -y graphviz --version=2.38.0.20190211 ;;
          *) echo "Unsupported OS"; exit 1 ;;
        esac

    - name: Python dependencies
      shell: bash
      run: |
        # explicitly install numpy (https://github.com/pypa/pip/issues/9239)
        python -m pip install --upgrade pip wheel $(grep numpy requirements.txt)
        pip install -e .[${{ inputs.features }}]

